// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrIbK-J1bbbeQraTuz6_xtLeLpXUwXheI',
    appId: '1:801038800723:web:0a182257977a978546f3a6',
    messagingSenderId: '801038800723',
    projectId: 'my-task-planning-app',
    authDomain: 'my-task-planning-app.firebaseapp.com',
    storageBucket: 'my-task-planning-app.firebasestorage.app',
    measurementId: 'G-4PE0Z64C8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcu3Xg6stJCGzvvsnKa719pq1PedQQWy8',
    appId: '1:801038800723:android:010e08adb808a98e46f3a6',
    messagingSenderId: '801038800723',
    projectId: 'my-task-planning-app',
    storageBucket: 'my-task-planning-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAif2WxxiajQ7YBM4oj9VJ9NwQU9cbPo0s',
    appId: '1:801038800723:ios:eee0d24b14f7482746f3a6',
    messagingSenderId: '801038800723',
    projectId: 'my-task-planning-app',
    storageBucket: 'my-task-planning-app.firebasestorage.app',
    iosBundleId: 'com.example.taskPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAif2WxxiajQ7YBM4oj9VJ9NwQU9cbPo0s',
    appId: '1:801038800723:ios:eee0d24b14f7482746f3a6',
    messagingSenderId: '801038800723',
    projectId: 'my-task-planning-app',
    storageBucket: 'my-task-planning-app.firebasestorage.app',
    iosBundleId: 'com.example.taskPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrIbK-J1bbbeQraTuz6_xtLeLpXUwXheI',
    appId: '1:801038800723:web:48f7b5845ea0ecb246f3a6',
    messagingSenderId: '801038800723',
    projectId: 'my-task-planning-app',
    authDomain: 'my-task-planning-app.firebaseapp.com',
    storageBucket: 'my-task-planning-app.firebasestorage.app',
    measurementId: 'G-KYJ5JZB6L7',
  );
}
